# Generated by Django 4.2.23 on 2025-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_company_body_company_resume_company_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='media')),
                ('subject', models.CharField(max_length=250, null=True)),
                ('body', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='body',
        ),
        migrations.RemoveField(
            model_name='company',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subject',
        ),
    ]
